language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run clean-force
  - npm run remove-modules
  - npm run install-npm
  - npm install --save-dev gh-pages
  - npm test --passWithNoTests
  - npm run build
  - npm run deploy
