language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run clean-force
  - npm run remove-modules
  - npm run install-npm
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master
